/**
 * Generated audio delivered by the ElevenLabs pipeline in tools/audio/.
 *
 * Effects and the default music bed are optional preloads: failure falls back
 * to procedural audio and never blocks the farm. The four alternate music
 * loops stay lazy so they do not add roughly 15.6 MB to startup or decoded memory.
 */
import type { AssetEntry } from './types.js';

export const AUDIO_ASSETS: readonly AssetEntry[] = [
  {
    id: 'animal.chicken',
    kind: 'audio',
    url: 'assets/audio/sfx/animal_chicken.mp3',
    phase: 'preload',
    bytes: 9_762,
    options: { durationSeconds: 0.747, bus: 'sfx' },
  },
  {
    id: 'animal.fox_alert',
    kind: 'audio',
    url: 'assets/audio/sfx/animal_fox_alert.mp3',
    phase: 'preload',
    bytes: 9_762,
    options: { durationSeconds: 0.75, bus: 'ui' },
  },
  {
    id: 'animal.fox_flee',
    kind: 'audio',
    url: 'assets/audio/sfx/animal_fox_flee.mp3',
    phase: 'preload',
    bytes: 12_270,
    options: { durationSeconds: 0.95, bus: 'sfx' },
  },
  {
    id: 'animal.raid_loss',
    kind: 'audio',
    url: 'assets/audio/sfx/animal_raid_loss.mp3',
    phase: 'preload',
    bytes: 16_345,
    options: { durationSeconds: 1.3, bus: 'sfx' },
  },
  {
    id: 'event.impact',
    kind: 'audio',
    url: 'assets/audio/sfx/event_impact.mp3',
    phase: 'preload',
    bytes: 24_809,
    options: { durationSeconds: 1.987, bus: 'sfx' },
  },
  {
    id: 'event.prevented',
    kind: 'audio',
    url: 'assets/audio/sfx/event_prevented.mp3',
    phase: 'preload',
    bytes: 15_091,
    options: { durationSeconds: 1.2, bus: 'sfx' },
  },
  {
    id: 'event.warning',
    kind: 'audio',
    url: 'assets/audio/sfx/event_warning.mp3',
    phase: 'preload',
    bytes: 22_301,
    options: { durationSeconds: 1.8, bus: 'ui' },
  },
  {
    id: 'farm.build_complete',
    kind: 'audio',
    url: 'assets/audio/sfx/farm_build_complete.mp3',
    phase: 'preload',
    bytes: 18_853,
    options: { durationSeconds: 1.5, bus: 'sfx' },
  },
  {
    id: 'farm.build_place',
    kind: 'audio',
    url: 'assets/audio/sfx/farm_build_place.mp3',
    phase: 'preload',
    bytes: 9_135,
    options: { durationSeconds: 0.7, bus: 'sfx' },
  },
  {
    id: 'farm.footstep',
    kind: 'audio',
    url: 'assets/audio/sfx/farm_footstep.mp3',
    phase: 'preload',
    bytes: 5_060,
    options: { durationSeconds: 0.35, bus: 'sfx' },
  },
  {
    id: 'farm.harvest',
    kind: 'audio',
    url: 'assets/audio/sfx/farm_harvest.mp3',
    phase: 'preload',
    bytes: 14_151,
    options: { durationSeconds: 1.1, bus: 'sfx' },
  },
  {
    id: 'farm.plant',
    kind: 'audio',
    url: 'assets/audio/sfx/farm_plant.mp3',
    phase: 'preload',
    bytes: 9_762,
    options: { durationSeconds: 0.75, bus: 'sfx' },
  },
  {
    id: 'farm.tend',
    kind: 'audio',
    url: 'assets/audio/sfx/farm_tend.mp3',
    phase: 'preload',
    bytes: 12_270,
    options: { durationSeconds: 0.95, bus: 'sfx' },
  },
  {
    id: 'goal.land_purchased',
    kind: 'audio',
    url: 'assets/audio/sfx/goal_land_purchased.mp3',
    phase: 'preload',
    bytes: 28_570,
    options: { durationSeconds: 2.3, bus: 'ui' },
  },
  {
    id: 'market.big_payout',
    kind: 'audio',
    url: 'assets/audio/sfx/market_big_payout.mp3',
    phase: 'preload',
    bytes: 21_360,
    options: { durationSeconds: 1.7, bus: 'sfx' },
  },
  {
    id: 'market.contract',
    kind: 'audio',
    url: 'assets/audio/sfx/market_contract.mp3',
    phase: 'preload',
    bytes: 16_345,
    options: { durationSeconds: 1.3, bus: 'sfx' },
  },
  {
    id: 'market.sell',
    kind: 'audio',
    url: 'assets/audio/sfx/market_sell.mp3',
    phase: 'preload',
    bytes: 12_270,
    options: { durationSeconds: 0.95, bus: 'sfx' },
  },
  {
    id: 'music.golden_harvest',
    kind: 'audio',
    url: 'assets/audio/music/golden_harvest.mp3',
    phase: 'lazy',
    bytes: 3_956_781,
    options: { durationSeconds: 247.247, bus: 'music', loop: true },
  },
  {
    id: 'music.market_day',
    kind: 'audio',
    url: 'assets/audio/music/market_day.mp3',
    phase: 'lazy',
    bytes: 3_841_197,
    options: { durationSeconds: 240.024, bus: 'music', loop: true },
  },
  {
    id: 'music.quiet_outback',
    kind: 'audio',
    url: 'assets/audio/music/quiet_outback.mp3',
    phase: 'lazy',
    bytes: 3_841_197,
    options: { durationSeconds: 240.017, bus: 'music', loop: true },
  },
  {
    id: 'music.rain_on_tin',
    kind: 'audio',
    url: 'assets/audio/music/rain_on_tin.mp3',
    phase: 'lazy',
    bytes: 3_975_981,
    options: { durationSeconds: 248.432, bus: 'music', loop: true },
  },
  {
    id: 'music.sunrise_rows',
    kind: 'audio',
    url: 'assets/audio/music/sunrise_rows.mp3',
    phase: 'preload',
    bytes: 3_841_581,
    options: { durationSeconds: 240.032, bus: 'music', loop: true },
  },
  {
    id: 'run.fail',
    kind: 'audio',
    url: 'assets/audio/sfx/run_fail.mp3',
    phase: 'preload',
    bytes: 27_316,
    options: { durationSeconds: 2.2, bus: 'ui' },
  },
  {
    id: 'run.success',
    kind: 'audio',
    url: 'assets/audio/sfx/run_success.mp3',
    phase: 'preload',
    bytes: 30_765,
    options: { durationSeconds: 2.5, bus: 'ui' },
  },
  {
    id: 'ui.click',
    kind: 'audio',
    url: 'assets/audio/sfx/ui_click.mp3',
    phase: 'preload',
    bytes: 2_866,
    options: { durationSeconds: 0.18, bus: 'ui' },
  },
  {
    id: 'ui.confirm',
    kind: 'audio',
    url: 'assets/audio/sfx/ui_confirm.mp3',
    phase: 'preload',
    bytes: 8_508,
    options: { durationSeconds: 0.65, bus: 'ui' },
  },
  {
    id: 'ui.deny',
    kind: 'audio',
    url: 'assets/audio/sfx/ui_deny.mp3',
    phase: 'preload',
    bytes: 6_941,
    options: { durationSeconds: 0.5, bus: 'ui' },
  },
  {
    id: 'ui.open',
    kind: 'audio',
    url: 'assets/audio/sfx/ui_open.mp3',
    phase: 'preload',
    bytes: 8_508,
    options: { durationSeconds: 0.65, bus: 'ui' },
  },
];
