/**
 * Generated audio delivered by the ElevenLabs pipeline in tools/audio/.
 *
 * Effects and the default music bed are optional preloads: failure falls back
 * to procedural audio and never blocks the farm. The four alternate music
 * loops stay lazy so they do not add roughly 15.6 MB to startup or decoded memory.
 */
import type { AssetEntry } from './types.js';
import { REFERENCE_ANIMAL_AUDIO_ASSETS } from './animalAudio.manifest.js';

export const AUDIO_ASSETS: readonly AssetEntry[] = [
  ...REFERENCE_ANIMAL_AUDIO_ASSETS,
  {
    id: 'animal.chicken',
    kind: 'audio',
    url: 'assets/audio/sfx/animal_chicken.mp3',
    phase: 'preload',
    bytes: 9_762,
    options: { durationSeconds: 0.747, bus: 'sfx' },
  },
  {
    id: 'animal.cow',
    kind: 'audio',
    url: 'assets/audio/sfx/animal_cow.mp3',
    phase: 'preload',
    bytes: 19_793,
    options: { durationSeconds: 1.59, bus: 'sfx' },
  },
  {
    id: 'animal.fox_alert',
    kind: 'audio',
    url: 'assets/audio/sfx/animal_fox_alert.mp3',
    phase: 'preload',
    bytes: 9_762,
    options: { durationSeconds: 0.75, bus: 'ui' },
  },
  {
    id: 'animal.fox_flee',
    kind: 'audio',
    url: 'assets/audio/sfx/animal_fox_flee.mp3',
    phase: 'preload',
    bytes: 12_270,
    options: { durationSeconds: 0.95, bus: 'sfx' },
  },
  {
    id: 'animal.raid_loss',
    kind: 'audio',
    url: 'assets/audio/sfx/animal_raid_loss.mp3',
    phase: 'preload',
    bytes: 16_345,
    options: { durationSeconds: 1.3, bus: 'sfx' },
  },
  {
    id: 'animal.sheep',
    kind: 'audio',
    url: 'assets/audio/sfx/animal_sheep.mp3',
    phase: 'preload',
    bytes: 15_091,
    options: { durationSeconds: 1.19, bus: 'sfx' },
  },
  {
    id: 'event.impact',
    kind: 'audio',
    url: 'assets/audio/sfx/event_impact.mp3',
    phase: 'preload',
    bytes: 24_809,
    options: { durationSeconds: 1.987, bus: 'sfx' },
  },
  {
    id: 'event.prevented',
    kind: 'audio',
    url: 'assets/audio/sfx/event_prevented.mp3',
    phase: 'preload',
    bytes: 15_091,
    options: { durationSeconds: 1.2, bus: 'sfx' },
  },
  {
    id: 'event.warning',
    kind: 'audio',
    url: 'assets/audio/sfx/event_warning.mp3',
    phase: 'preload',
    bytes: 22_301,
    options: { durationSeconds: 1.8, bus: 'ui' },
  },
  {
    id: 'farm.build_complete',
    kind: 'audio',
    url: 'assets/audio/sfx/farm_build_complete.mp3',
    phase: 'preload',
    bytes: 18_853,
    options: { durationSeconds: 1.5, bus: 'sfx' },
  },
  {
    id: 'farm.build_place',
    kind: 'audio',
    url: 'assets/audio/sfx/farm_build_place.mp3',
    phase: 'preload',
    bytes: 9_135,
    options: { durationSeconds: 0.7, bus: 'sfx' },
  },
  {
    id: 'farm.cart_roll',
    kind: 'audio',
    url: 'assets/audio/sfx/farm_cart_roll.mp3',
    phase: 'preload',
    bytes: 10_389,
    options: { durationSeconds: 0.79, bus: 'sfx' },
  },
  {
    id: 'farm.deposit',
    kind: 'audio',
    url: 'assets/audio/sfx/farm_deposit.mp3',
    phase: 'preload',
    bytes: 11_329,
    options: { durationSeconds: 0.87, bus: 'sfx' },
  },
  {
    id: 'farm.footstep',
    kind: 'audio',
    url: 'assets/audio/sfx/farm_footstep.mp3',
    phase: 'preload',
    bytes: 5_060,
    options: { durationSeconds: 0.35, bus: 'sfx' },
  },
  {
    id: 'farm.harvest',
    kind: 'audio',
    url: 'assets/audio/sfx/farm_harvest.mp3',
    phase: 'preload',
    bytes: 14_151,
    options: { durationSeconds: 1.1, bus: 'sfx' },
  },
  {
    id: 'farm.plant',
    kind: 'audio',
    url: 'assets/audio/sfx/farm_plant.mp3',
    phase: 'preload',
    bytes: 9_762,
    options: { durationSeconds: 0.75, bus: 'sfx' },
  },
  {
    id: 'farm.pickup',
    kind: 'audio',
    url: 'assets/audio/sfx/farm_pickup.mp3',
    phase: 'preload',
    bytes: 11_329,
    options: { durationSeconds: 0.87, bus: 'sfx' },
  },
  {
    id: 'farm.repair',
    kind: 'audio',
    url: 'assets/audio/sfx/farm_repair.mp3',
    phase: 'preload',
    bytes: 16_031,
    options: { durationSeconds: 1.27, bus: 'sfx' },
  },
  {
    id: 'farm.shoo_animals',
    kind: 'audio',
    url: 'assets/audio/sfx/farm_shoo_animals.mp3',
    phase: 'preload',
    bytes: 15_091,
    options: { durationSeconds: 1.19, bus: 'sfx' },
  },
  {
    id: 'farm.tend',
    kind: 'audio',
    url: 'assets/audio/sfx/farm_tend.mp3',
    phase: 'preload',
    bytes: 12_270,
    options: { durationSeconds: 0.95, bus: 'sfx' },
  },
  {
    id: 'goal.land_purchased',
    kind: 'audio',
    url: 'assets/audio/sfx/goal_land_purchased.mp3',
    phase: 'preload',
    bytes: 28_570,
    options: { durationSeconds: 2.3, bus: 'ui' },
  },
  {
    id: 'incident.blight_impact',
    kind: 'audio',
    url: 'assets/audio/sfx/incident_blight_impact.mp3',
    phase: 'preload',
    bytes: 20_734,
    options: { durationSeconds: 1.67, bus: 'sfx' },
  },
  {
    id: 'incident.blight_warning',
    kind: 'audio',
    url: 'assets/audio/sfx/incident_blight_warning.mp3',
    phase: 'preload',
    bytes: 18_539,
    options: { durationSeconds: 1.47, bus: 'ui' },
  },
  {
    id: 'incident.cart_axle_impact',
    kind: 'audio',
    url: 'assets/audio/sfx/incident_cart_axle_impact.mp3',
    phase: 'preload',
    bytes: 19_793,
    options: { durationSeconds: 1.59, bus: 'sfx' },
  },
  {
    id: 'incident.cart_axle_warning',
    kind: 'audio',
    url: 'assets/audio/sfx/incident_cart_axle_warning.mp3',
    phase: 'preload',
    bytes: 19_793,
    options: { durationSeconds: 1.59, bus: 'ui' },
  },
  {
    id: 'incident.cold_snap_impact',
    kind: 'audio',
    url: 'assets/audio/sfx/incident_cold_snap_impact.mp3',
    phase: 'preload',
    bytes: 21_674,
    options: { durationSeconds: 1.75, bus: 'sfx' },
  },
  {
    id: 'incident.cold_snap_warning',
    kind: 'audio',
    url: 'assets/audio/sfx/incident_cold_snap_warning.mp3',
    phase: 'preload',
    bytes: 21_674,
    options: { durationSeconds: 1.75, bus: 'ui' },
  },
  {
    id: 'incident.drought_impact',
    kind: 'audio',
    url: 'assets/audio/sfx/incident_drought_impact.mp3',
    phase: 'preload',
    bytes: 21_674,
    options: { durationSeconds: 1.75, bus: 'sfx' },
  },
  {
    id: 'incident.drought_warning',
    kind: 'audio',
    url: 'assets/audio/sfx/incident_drought_warning.mp3',
    phase: 'preload',
    bytes: 30_451,
    options: { durationSeconds: 2.47, bus: 'ui' },
  },
  {
    id: 'incident.fox_raid_warning',
    kind: 'audio',
    url: 'assets/audio/sfx/incident_fox_raid_warning.mp3',
    phase: 'preload',
    bytes: 16_972,
    options: { durationSeconds: 1.35, bus: 'ui' },
  },
  {
    id: 'incident.processor_breakdown_impact',
    kind: 'audio',
    url: 'assets/audio/sfx/incident_processor_breakdown_impact.mp3',
    phase: 'preload',
    bytes: 21_674,
    options: { durationSeconds: 1.75, bus: 'sfx' },
  },
  {
    id: 'incident.processor_breakdown_warning',
    kind: 'audio',
    url: 'assets/audio/sfx/incident_processor_breakdown_warning.mp3',
    phase: 'preload',
    bytes: 20_734,
    options: { durationSeconds: 1.67, bus: 'ui' },
  },
  {
    id: 'incident.road_washout_impact',
    kind: 'audio',
    url: 'assets/audio/sfx/incident_road_washout_impact.mp3',
    phase: 'preload',
    bytes: 24_182,
    options: { durationSeconds: 1.938, bus: 'sfx' },
  },
  {
    id: 'incident.road_washout_warning',
    kind: 'audio',
    url: 'assets/audio/sfx/incident_road_washout_warning.mp3',
    phase: 'preload',
    bytes: 21_674,
    options: { durationSeconds: 1.75, bus: 'ui' },
  },
  {
    id: 'market.big_payout',
    kind: 'audio',
    url: 'assets/audio/sfx/market_big_payout.mp3',
    phase: 'preload',
    bytes: 21_360,
    options: { durationSeconds: 1.7, bus: 'sfx' },
  },
  {
    id: 'market.contract',
    kind: 'audio',
    url: 'assets/audio/sfx/market_contract.mp3',
    phase: 'preload',
    bytes: 16_345,
    options: { durationSeconds: 1.3, bus: 'sfx' },
  },
  {
    id: 'market.sell',
    kind: 'audio',
    url: 'assets/audio/sfx/market_sell.mp3',
    phase: 'preload',
    bytes: 12_270,
    options: { durationSeconds: 0.95, bus: 'sfx' },
  },
  {
    id: 'music.golden_harvest',
    kind: 'audio',
    url: 'assets/audio/music/golden_harvest.mp3',
    phase: 'lazy',
    bytes: 3_956_781,
    options: { durationSeconds: 247.247, bus: 'music', loop: true },
  },
  {
    id: 'music.market_day',
    kind: 'audio',
    url: 'assets/audio/music/market_day.mp3',
    phase: 'lazy',
    bytes: 3_841_197,
    options: { durationSeconds: 240.024, bus: 'music', loop: true },
  },
  {
    id: 'music.quiet_outback',
    kind: 'audio',
    url: 'assets/audio/music/quiet_outback.mp3',
    phase: 'lazy',
    bytes: 3_841_197,
    options: { durationSeconds: 240.017, bus: 'music', loop: true },
  },
  {
    id: 'music.rain_on_tin',
    kind: 'audio',
    url: 'assets/audio/music/rain_on_tin.mp3',
    phase: 'lazy',
    bytes: 3_975_981,
    options: { durationSeconds: 248.432, bus: 'music', loop: true },
  },
  {
    id: 'music.sunrise_rows',
    kind: 'audio',
    url: 'assets/audio/music/sunrise_rows.mp3',
    phase: 'preload',
    bytes: 3_841_581,
    options: { durationSeconds: 240.032, bus: 'music', loop: true },
  },
  {
    id: 'processing.complete',
    kind: 'audio',
    url: 'assets/audio/sfx/processing_complete.mp3',
    phase: 'preload',
    bytes: 29_511,
    options: { durationSeconds: 2.39, bus: 'sfx' },
  },
  {
    id: 'processing.start',
    kind: 'audio',
    url: 'assets/audio/sfx/processing_start.mp3',
    phase: 'preload',
    bytes: 19_793,
    options: { durationSeconds: 1.59, bus: 'sfx' },
  },
  {
    id: 'run.fail',
    kind: 'audio',
    url: 'assets/audio/sfx/run_fail.mp3',
    phase: 'preload',
    bytes: 27_316,
    options: { durationSeconds: 2.2, bus: 'ui' },
  },
  {
    id: 'run.success',
    kind: 'audio',
    url: 'assets/audio/sfx/run_success.mp3',
    phase: 'preload',
    bytes: 30_765,
    options: { durationSeconds: 2.5, bus: 'ui' },
  },
  {
    id: 'season.transition',
    kind: 'audio',
    url: 'assets/audio/sfx/season_transition.mp3',
    phase: 'preload',
    bytes: 39_228,
    options: { durationSeconds: 3.19, bus: 'ui' },
  },
  {
    id: 'ui.click',
    kind: 'audio',
    url: 'assets/audio/sfx/ui_click.mp3',
    phase: 'preload',
    bytes: 2_866,
    options: { durationSeconds: 0.18, bus: 'ui' },
  },
  {
    id: 'ui.confirm',
    kind: 'audio',
    url: 'assets/audio/sfx/ui_confirm.mp3',
    phase: 'preload',
    bytes: 8_508,
    options: { durationSeconds: 0.65, bus: 'ui' },
  },
  {
    id: 'ui.deny',
    kind: 'audio',
    url: 'assets/audio/sfx/ui_deny.mp3',
    phase: 'preload',
    bytes: 6_941,
    options: { durationSeconds: 0.5, bus: 'ui' },
  },
  {
    id: 'ui.open',
    kind: 'audio',
    url: 'assets/audio/sfx/ui_open.mp3',
    phase: 'preload',
    bytes: 8_508,
    options: { durationSeconds: 0.65, bus: 'ui' },
  },
];
