/**
 * Procedural PBR surface textures. GENERATED FILE - do not hand-edit.
 *
 * Regenerate with `node tools/textures/generate.mjs`. The patterns live in
 * tools/textures/materials.mjs and the rationale in art/textures/README.md.
 *
 * Every entry is `lazy`: SurfaceLibrary is constructed only on the Ultra tier,
 * so on `low` none of these bytes are ever requested.
 *
 * Total: 967.1 KiB across 10 materials.
 */
import type { AssetEntry } from './types.js';

export const SURFACE_TEXTURE_ASSETS: readonly AssetEntry[] = [
  {
    id: 'texture:soil_dry_cracked_albedo',
    kind: 'texture',
    url: 'assets/textures/soil_dry_cracked_albedo.png',
    phase: 'lazy',
    bytes: 31_590,
    scenes: ['farm'],
    options: { colorSpace: 'srgb', flipY: false, anisotropy: 8 },
  },
  {
    id: 'texture:soil_dry_cracked_normal',
    kind: 'texture',
    url: 'assets/textures/soil_dry_cracked_normal.png',
    phase: 'lazy',
    bytes: 98_752,
    scenes: ['farm'],
    options: { colorSpace: 'linear', flipY: false, anisotropy: 8 },
  },
  {
    id: 'texture:soil_dry_cracked_orm',
    kind: 'texture',
    url: 'assets/textures/soil_dry_cracked_orm.png',
    phase: 'lazy',
    bytes: 24_977,
    scenes: ['farm'],
    options: { colorSpace: 'linear', flipY: false, anisotropy: 8 },
  },
  {
    id: 'texture:soil_tilled_albedo',
    kind: 'texture',
    url: 'assets/textures/soil_tilled_albedo.png',
    phase: 'lazy',
    bytes: 28_083,
    scenes: ['farm'],
    options: { colorSpace: 'srgb', flipY: false, anisotropy: 8 },
  },
  {
    id: 'texture:soil_tilled_normal',
    kind: 'texture',
    url: 'assets/textures/soil_tilled_normal.png',
    phase: 'lazy',
    bytes: 95_741,
    scenes: ['farm'],
    options: { colorSpace: 'linear', flipY: false, anisotropy: 8 },
  },
  {
    id: 'texture:soil_tilled_orm',
    kind: 'texture',
    url: 'assets/textures/soil_tilled_orm.png',
    phase: 'lazy',
    bytes: 20_952,
    scenes: ['farm'],
    options: { colorSpace: 'linear', flipY: false, anisotropy: 8 },
  },
  {
    id: 'texture:grass_dry_albedo',
    kind: 'texture',
    url: 'assets/textures/grass_dry_albedo.png',
    phase: 'lazy',
    bytes: 41_452,
    scenes: ['farm'],
    options: { colorSpace: 'srgb', flipY: false, anisotropy: 8 },
  },
  {
    id: 'texture:grass_dry_normal',
    kind: 'texture',
    url: 'assets/textures/grass_dry_normal.png',
    phase: 'lazy',
    bytes: 120_151,
    scenes: ['farm'],
    options: { colorSpace: 'linear', flipY: false, anisotropy: 8 },
  },
  {
    id: 'texture:grass_dry_orm',
    kind: 'texture',
    url: 'assets/textures/grass_dry_orm.png',
    phase: 'lazy',
    bytes: 21_165,
    scenes: ['farm'],
    options: { colorSpace: 'linear', flipY: false, anisotropy: 8 },
  },
  {
    id: 'texture:scrub_gravel_albedo',
    kind: 'texture',
    url: 'assets/textures/scrub_gravel_albedo.png',
    phase: 'lazy',
    bytes: 20_951,
    scenes: ['farm'],
    options: { colorSpace: 'srgb', flipY: false, anisotropy: 8 },
  },
  {
    id: 'texture:scrub_gravel_normal',
    kind: 'texture',
    url: 'assets/textures/scrub_gravel_normal.png',
    phase: 'lazy',
    bytes: 60_649,
    scenes: ['farm'],
    options: { colorSpace: 'linear', flipY: false, anisotropy: 8 },
  },
  {
    id: 'texture:scrub_gravel_orm',
    kind: 'texture',
    url: 'assets/textures/scrub_gravel_orm.png',
    phase: 'lazy',
    bytes: 18_428,
    scenes: ['farm'],
    options: { colorSpace: 'linear', flipY: false, anisotropy: 8 },
  },
  {
    id: 'texture:bark_eucalyptus_albedo',
    kind: 'texture',
    url: 'assets/textures/bark_eucalyptus_albedo.png',
    phase: 'lazy',
    bytes: 16_826,
    scenes: ['farm'],
    options: { colorSpace: 'srgb', flipY: false, anisotropy: 8 },
  },
  {
    id: 'texture:bark_eucalyptus_normal',
    kind: 'texture',
    url: 'assets/textures/bark_eucalyptus_normal.png',
    phase: 'lazy',
    bytes: 69_074,
    scenes: ['farm'],
    options: { colorSpace: 'linear', flipY: false, anisotropy: 8 },
  },
  {
    id: 'texture:bark_eucalyptus_orm',
    kind: 'texture',
    url: 'assets/textures/bark_eucalyptus_orm.png',
    phase: 'lazy',
    bytes: 16_307,
    scenes: ['farm'],
    options: { colorSpace: 'linear', flipY: false, anisotropy: 8 },
  },
  {
    id: 'texture:timber_painted_albedo',
    kind: 'texture',
    url: 'assets/textures/timber_painted_albedo.png',
    phase: 'lazy',
    bytes: 13_644,
    scenes: ['farm'],
    options: { colorSpace: 'srgb', flipY: false, anisotropy: 8 },
  },
  {
    id: 'texture:timber_painted_normal',
    kind: 'texture',
    url: 'assets/textures/timber_painted_normal.png',
    phase: 'lazy',
    bytes: 38_924,
    scenes: ['farm'],
    options: { colorSpace: 'linear', flipY: false, anisotropy: 8 },
  },
  {
    id: 'texture:timber_painted_orm',
    kind: 'texture',
    url: 'assets/textures/timber_painted_orm.png',
    phase: 'lazy',
    bytes: 13_596,
    scenes: ['farm'],
    options: { colorSpace: 'linear', flipY: false, anisotropy: 8 },
  },
  {
    id: 'texture:metal_corrugated_albedo',
    kind: 'texture',
    url: 'assets/textures/metal_corrugated_albedo.png',
    phase: 'lazy',
    bytes: 2_497,
    scenes: ['farm'],
    options: { colorSpace: 'srgb', flipY: false, anisotropy: 8 },
  },
  {
    id: 'texture:metal_corrugated_normal',
    kind: 'texture',
    url: 'assets/textures/metal_corrugated_normal.png',
    phase: 'lazy',
    bytes: 7_995,
    scenes: ['farm'],
    options: { colorSpace: 'linear', flipY: false, anisotropy: 8 },
  },
  {
    id: 'texture:metal_corrugated_orm',
    kind: 'texture',
    url: 'assets/textures/metal_corrugated_orm.png',
    phase: 'lazy',
    bytes: 3_792,
    scenes: ['farm'],
    options: { colorSpace: 'linear', flipY: false, anisotropy: 8 },
  },
  {
    id: 'texture:roof_shingle_albedo',
    kind: 'texture',
    url: 'assets/textures/roof_shingle_albedo.png',
    phase: 'lazy',
    bytes: 22_580,
    scenes: ['farm'],
    options: { colorSpace: 'srgb', flipY: false, anisotropy: 8 },
  },
  {
    id: 'texture:roof_shingle_normal',
    kind: 'texture',
    url: 'assets/textures/roof_shingle_normal.png',
    phase: 'lazy',
    bytes: 84_632,
    scenes: ['farm'],
    options: { colorSpace: 'linear', flipY: false, anisotropy: 8 },
  },
  {
    id: 'texture:roof_shingle_orm',
    kind: 'texture',
    url: 'assets/textures/roof_shingle_orm.png',
    phase: 'lazy',
    bytes: 21_088,
    scenes: ['farm'],
    options: { colorSpace: 'linear', flipY: false, anisotropy: 8 },
  },
  {
    id: 'texture:cloth_canvas_albedo',
    kind: 'texture',
    url: 'assets/textures/cloth_canvas_albedo.png',
    phase: 'lazy',
    bytes: 10_706,
    scenes: ['farm'],
    options: { colorSpace: 'srgb', flipY: false, anisotropy: 8 },
  },
  {
    id: 'texture:cloth_canvas_normal',
    kind: 'texture',
    url: 'assets/textures/cloth_canvas_normal.png',
    phase: 'lazy',
    bytes: 33_398,
    scenes: ['farm'],
    options: { colorSpace: 'linear', flipY: false, anisotropy: 8 },
  },
  {
    id: 'texture:cloth_canvas_orm',
    kind: 'texture',
    url: 'assets/textures/cloth_canvas_orm.png',
    phase: 'lazy',
    bytes: 7_319,
    scenes: ['farm'],
    options: { colorSpace: 'linear', flipY: false, anisotropy: 8 },
  },
  {
    id: 'texture:fur_short_albedo',
    kind: 'texture',
    url: 'assets/textures/fur_short_albedo.png',
    phase: 'lazy',
    bytes: 9_972,
    scenes: ['farm'],
    options: { colorSpace: 'srgb', flipY: false, anisotropy: 8 },
  },
  {
    id: 'texture:fur_short_normal',
    kind: 'texture',
    url: 'assets/textures/fur_short_normal.png',
    phase: 'lazy',
    bytes: 28_225,
    scenes: ['farm'],
    options: { colorSpace: 'linear', flipY: false, anisotropy: 8 },
  },
  {
    id: 'texture:fur_short_orm',
    kind: 'texture',
    url: 'assets/textures/fur_short_orm.png',
    phase: 'lazy',
    bytes: 6_893,
    scenes: ['farm'],
    options: { colorSpace: 'linear', flipY: false, anisotropy: 8 },
  },
];

/** Material ids in the library, in the order they were generated. */
export const SURFACE_IDS = [
  'soil_dry_cracked',
  'soil_tilled',
  'grass_dry',
  'scrub_gravel',
  'bark_eucalyptus',
  'timber_painted',
  'metal_corrugated',
  'roof_shingle',
  'cloth_canvas',
  'fur_short',
] as const;

export type SurfaceId = (typeof SURFACE_IDS)[number];
