/** Blender-rendered DOM interface art. Generated by `npm run art:ui-icons`. */
import type { AssetEntry } from './types.js';

export const UI_ICON_URLS = {
  heroFarm: 'assets/ui/icons/hero-farm.webp',
  farmer: 'assets/ui/icons/farmer.webp',
  settings: 'assets/ui/icons/settings.webp',
  market: 'assets/ui/icons/market.webp',
  contract: 'assets/ui/icons/contract.webp',
  wheat: 'assets/ui/icons/wheat.webp',
  corn: 'assets/ui/icons/corn.webp',
  pumpkin: 'assets/ui/icons/pumpkin.webp',
  eggs: 'assets/ui/icons/eggs.webp',
  barn: 'assets/ui/icons/barn.webp',
  irrigation: 'assets/ui/icons/irrigation.webp',
  road: 'assets/ui/icons/road.webp',
  fence: 'assets/ui/icons/fence.webp',
  chicken: 'assets/ui/icons/chicken.webp',
  land: 'assets/ui/icons/land.webp',
  warning: 'assets/ui/icons/warning.webp',
  watering: 'assets/ui/icons/watering.webp',
  harvest: 'assets/ui/icons/harvest.webp',
  tools: 'assets/ui/icons/tools.webp',
} as const;

export type UiIconId = keyof typeof UI_ICON_URLS;

const BYTES: Record<UiIconId, number> = {
  heroFarm: 11_080,
  farmer: 4_330,
  settings: 4_424,
  market: 5_804,
  contract: 4_060,
  wheat: 9_128,
  corn: 8_348,
  pumpkin: 2_780,
  eggs: 2_532,
  barn: 3_038,
  irrigation: 3_210,
  road: 1_656,
  fence: 3_280,
  chicken: 3_384,
  land: 3_120,
  warning: 2_828,
  watering: 3_068,
  harvest: 2_598,
  tools: 3_482,
};

export const UI_ICON_ASSETS: readonly AssetEntry[] = Object.entries(UI_ICON_URLS).map(
  ([id, url]) => ({
    id: `texture:ui-${id}`,
    kind: 'texture',
    url,
    phase: 'lazy' as const,
    bytes: BYTES[id as UiIconId],
  }),
);
